#!/usr/bin/env python3
"""Script -> AI voice (OpenAI TTS) + word-level timestamps for the scene.

Usage:
  python3 voz.py narracion.json              # generate missing sections, join, transcribe
  python3 voz.py narracion.json --solo s3    # regenerate one section (e.g. bad pronunciation)
  python3 voz.py --solo-tiempos audio.wav    # only word timestamps for an existing recording

Writes next to narracion.json: voz.wav, voz.js (window.VOZ) and transcripcion.txt.
"""
import argparse
import hashlib
import json
import sys
import tempfile
import wave
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from comun import ffmpeg, require_ffmpeg, require_key

RATE = 24000          # Hz, mono, 16-bit
GAP = 0.5             # seconds of silence between sections
TTS_MODEL = "gpt-4o-mini-tts"


def tts(key, text, voice, instructions, out):
    r = requests.post(
        "https://api.openai.com/v1/audio/speech",
        headers={"Authorization": f"Bearer {key}"},
        json={"model": TTS_MODEL, "voice": voice, "input": text,
              "instructions": instructions, "response_format": "mp3"},
        timeout=180,
    )
    if r.status_code != 200:
        sys.exit(f"Error de OpenAI TTS ({r.status_code}): {r.text[:300]}")
    out.write_bytes(r.content)


def to_pcm(src):
    """Decode any audio to raw 24 kHz mono s16 bytes."""
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "a.raw"
        ffmpeg("-i", src, "-f", "s16le", "-ac", 1, "-ar", RATE, raw)
        return raw.read_bytes()


def transcribe(key, audio):
    with tempfile.TemporaryDirectory() as tmp:
        mp3 = Path(tmp) / "a.mp3"
        ffmpeg("-i", audio, "-ac", 1, "-b:a", "64k", mp3)
        with open(mp3, "rb") as f:
            r = requests.post(
                "https://api.openai.com/v1/audio/transcriptions",
                headers={"Authorization": f"Bearer {key}"},
                files={"file": ("a.mp3", f, "audio/mpeg")},
                data=[("model", "whisper-1"), ("language", "es"),
                      ("response_format", "verbose_json"),
                      ("timestamp_granularities[]", "word")],
                timeout=300,
            )
    if r.status_code != 200:
        sys.exit(f"Error de OpenAI transcripción ({r.status_code}): {r.text[:300]}")
    return r.json()


def write_outputs(folder, total, sections, words, text):
    for w in words:
        w.setdefault("seccion", sections[0]["id"] if sections else None)
    data = {"duracion": round(total, 3), "secciones": sections, "palabras": words}
    (folder / "voz.js").write_text(
        "// Generated by voz.py — word timings of the voice-over.\nwindow.VOZ = "
        + json.dumps(data, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")

    lines = [f"Duración total: {total:.1f} s\n",
             ("Lo que entendió el reconocedor de voz (si una palabra sale mal aquí, escucha esa "
              "sección: puede ser la voz o el reconocedor):\n")]
    for s in sections:
        heard = " ".join(w["texto"] for w in words if w["seccion"] == s["id"])
        lines.append(f"[{s['id']}] {s['inicio']:.1f}–{s['fin']:.1f} s\n  guion: {s['texto']}\n  oído:  {heard}\n")
    if not sections:
        lines.append(text)
    (folder / "transcripcion.txt").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"Listo: {folder / 'voz.wav'} · {folder / 'voz.js'} · {folder / 'transcripcion.txt'}")


def words_from(result):
    return [{"texto": w["word"].strip(), "inicio": round(w["start"], 3), "fin": round(w["end"], 3)}
            for w in result.get("words", []) if w["word"].strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("narracion", nargs="?")
    ap.add_argument("--solo", help="regenerate only this section id")
    ap.add_argument("--solo-tiempos", help="existing recording: only compute word timings")
    a = ap.parse_args()
    require_ffmpeg()
    key = require_key()

    if a.solo_tiempos:
        audio = Path(a.solo_tiempos).resolve()
        folder = audio.parent
        if audio.name != "voz.wav":
            ffmpeg("-i", audio, "-ac", 1, "-ar", RATE, folder / "voz.wav")
        pcm = to_pcm(folder / "voz.wav")
        total = len(pcm) / 2 / RATE
        result = transcribe(key, folder / "voz.wav")
        sections = [{"id": "s1", "texto": result.get("text", ""), "inicio": 0.0, "fin": round(total, 3)}]
        write_outputs(folder, total, sections, words_from(result), result.get("text", ""))
        return

    if not a.narracion:
        ap.error("falta narracion.json")
    path = Path(a.narracion).resolve()
    folder = path.parent
    spec = json.loads(path.read_text(encoding="utf-8"))
    voice = spec.get("voz", "ash")
    instructions = spec.get("instrucciones", "Locutor latinoamericano, cálido y claro.")
    parts_dir = folder / "secciones"
    parts_dir.mkdir(exist_ok=True)

    pcm_all, sections, words, t = b"", [], [], 0.0
    silence = b"\x00\x00" * int(GAP * RATE)
    for s in spec["secciones"]:
        sid, text = s["id"], s["texto"].strip()
        mp3 = parts_dir / f"{sid}.mp3"
        stamp = parts_dir / f"{sid}.hash"
        h = hashlib.sha1(f"{voice}|{instructions}|{text}".encode()).hexdigest()
        if a.solo == sid or not mp3.exists() or not stamp.exists() or stamp.read_text() != h:
            print(f"Generando voz de {sid}…")
            tts(key, text, voice, instructions, mp3)
            stamp.write_text(h)
        cache = parts_dir / f"{sid}.palabras.json"
        if not cache.exists() or cache.stat().st_mtime < mp3.stat().st_mtime:
            cache.write_text(json.dumps(words_from(transcribe(key, mp3)), ensure_ascii=False))
        pcm = to_pcm(mp3)
        dur = len(pcm) / 2 / RATE
        sections.append({"id": sid, "texto": text, "inicio": round(t, 3), "fin": round(t + dur, 3)})
        for w in json.loads(cache.read_text(encoding="utf-8")):
            words.append({"texto": w["texto"], "inicio": round(min(w["inicio"], dur) + t, 3),
                          "fin": round(min(w["fin"], dur) + t, 3), "seccion": sid})
        pcm_all += pcm + silence
        t += dur + GAP

    with wave.open(str(folder / "voz.wav"), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(pcm_all)
    total = len(pcm_all) / 2 / RATE
    write_outputs(folder, total, sections, words, "")


if __name__ == "__main__":
    main()
